### ISSUE TITLE
Example App: Error while uploading invalid schema

### ISSUE THREAD

**Issue by lovellfelix** [jgilfelt/android-simpl3r#1]
Error: The XML you provided was not well formed or did not validate against our published schema. 

Not sure where to look for the upload schema, but I think it's set as 

./s3-put -T ./test2 -k <mykey> -s ./<mysecretkeyfile> /mybucketname

and it should be: 

./s3-put -T ./test2 -k <mykey> -s ./<mysecretkeyfile> /mybucketname/myfile

**Comment by jgilfelt** [comment]
You will get this error when selecting a media item from the gallery app rather than from a file provider. The path returned in the URI is not a local file path so the AmazonHttpClient will complain.

I don't use the media store projection to get the local path because I didn't wan't to include a bunch of code not related to the library in the example app, but I guess I will add it.
